### PR TITLE
Added a limited user to run our application process

### PR DESCRIPTION
**Pull request by neklaf**

### CODE REVIEW

**Comment by neklaf** [comment]
The point to change the port is due to if node process is owned for a limited user, that user can't bind process in privileged ports, so it's needed to increase the port number to be able to start the server.

**Comment by jmsampayo** [comment]
Oh! Got it! Then, we should change all ports, for PRO and TEST in order to use limited users in all the containers... right?

**Comment by neklaf** [comment]
I just want to create the modification in TEST Dockerfile and once you're agree it can be moved the same changes to PRO, it's the reason because I don't modify any additional file.

**Comment by jmsampayo** [comment]
Perfect! Let me update deployment scripts and architecture diagrams to non-priviledge ports. And also Nginx reverse proxy configurations... I will do it asap. Once done (this afternoon I think I can do it), we can merge this pull request and do a quick test. :-) Thanks @neklaf !

**Comment by neklaf** [comment]
Please let me know how I can help you, it seems a lot of work to do.

**Comment by neklaf** [comment]
Hi @jmsampayo,

Who has to review the PR? I feel like working in OneMP :)

**Pull request merged**
